# Generated by Django 3.2.16 on 2023-01-25 11:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="destination_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(
                default="", max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author_image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder",
                        max_length=255,
                        verbose_name="image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
