# Generated by Django 3.2.16 on 2023-01-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230125_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='blog.Destination'),
        ),
    ]
