# Generated by Django 3.2.16 on 2023-02-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20230214_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
