# Generated by Django 3.2.16 on 2023-03-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_author_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
