# Generated by Django 3.2.16 on 2023-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_ideal_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='best_time',
            field=models.CharField(max_length=100, verbose_name='Best time(Season/Month)'),
        ),
    ]
